### ISSUE TITLE
Issue with R1 and L1

### ISSUE THREAD

**Issue by Alacander** [AkikoKumagara/Naruto-STORM-3-PS-Icons#1]
L1 and R1 buttons don't work. They are not recognized even in the command options screen, when I press them I hear a sound but they don't work and I can't assign them to the supports as they should be.

**Comment by AkikoKumagara** [comment]
I've heard of issues like this happening before.
Here's what I'd like for you to try:

If STEAM INPUT is "off" for your gamepad and you're using a third-party tool such as DS4Windows, for example: Exit the third-party tool completely and enable Steam Input for your gamepad.

If STEAM INPUT is "on" for your gamepad and you're using a third-party tool such as DS4Windows: Disable either Steam Input (per game) or the third-party tool.

These are issues that are most likely the result of some sort of conflict. My mod should not affect gamepad behavior at all.

**Comment by Alacander** [comment]
Now I try

**Comment by Alacander** [comment]
TYVM for the quick answer

**Comment by Alacander** [comment]
And fixed! You had right, I had DS4+ Steam input, I closed DS4, closed and reopened Steam input, I've reverted the commands option to the default settings and now it's all right. TYVM :)

**Comment by AkikoKumagara** [comment]
> TYVM for the quick answer

Not a problem, you caught me at a good time!

**Comment by Alacander** [comment]
:)  ..Strange though, on Storm 1, 2, 4 and Connections I didn't have this problem. With your mods.
